"""Update relationship

Revision ID: 20ddaf59241c
Revises: 323c670215ff
Create Date: 2025-11-09 16:26:19.673499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ddaf59241c'
down_revision: Union[str, None] = '323c670215ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profilelikes',
    sa.Column('liker_id', sa.Integer(), nullable=False),
    sa.Column('liked_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('liker_id != liked_id', name='no_self_like'),
    sa.ForeignKeyConstraint(['liked_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liker_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('liker_id', 'liked_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profilelikes')
    # ### end Alembic commands ###
