"""Create tables

Revision ID: 323c670215ff
Revises:
Create Date: 2025-11-07 18:13:26.983452

"""

from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "323c670215ff"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_music_education():
    return postgresql.ENUM(
        "PRIMARY", "SECONDARY", "HIGHER", "SELF", name="musiceducation"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("faculty", sa.String(length=100), nullable=False),
        sa.Column("course", sa.Integer(), nullable=False),
        sa.Column(
            "education",
            sa.Enum("PRIMARY", "SECONDARY", "HIGHER", "SELF", name="musiceducation"),
            nullable=False,
        ),
        sa.Column("desc", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "instrumentitems",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"], ["instruments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id", "instrument_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("instrumentitems")
    op.drop_table("profiles")
    op.drop_table("instruments")
    _get_music_education().drop(op.get_bind())
    # ### end Alembic commands ###
