"""Update schema

Revision ID: 6f15ab4f3a9c
Revises: cab811dd91ed
Create Date: 2025-11-09 21:33:53.923000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f15ab4f3a9c'
down_revision: Union[str, None] = 'cab811dd91ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profilelikes',
    sa.Column('liker_id', sa.BigInteger(), nullable=False),
    sa.Column('liked_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['liked_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liker_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('liker_id', 'liked_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profilelikes')
    # ### end Alembic commands ###
