"""Update schema

Revision ID: ae1948a6727e
Revises: ca93b51cbe5a
Create Date: 2025-11-09 18:57:30.156384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1948a6727e'
down_revision: Union[str, None] = 'ca93b51cbe5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrumentitems')
    op.drop_table('instruments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('instruments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='instruments_pkey'),
    sa.UniqueConstraint('name', name='instruments_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('instrumentitems',
    sa.Column('profile_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('instrument_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('experience', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name='instrumentitems_instrument_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='instrumentitems_profile_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'instrument_id', name='instrumentitems_pkey')
    )
    # ### end Alembic commands ###
