"""Update schema

Revision ID: cab811dd91ed
Revises: ae1948a6727e
Create Date: 2025-11-09 20:41:02.614897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab811dd91ed'
down_revision: Union[str, None] = 'ae1948a6727e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profilelikes')
    op.add_column('profiles', sa.Column('username', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'username')
    op.create_table('profilelikes',
    sa.Column('liker_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('liked_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('liker_id <> liked_id', name='no_self_like'),
    sa.ForeignKeyConstraint(['liked_id'], ['profiles.id'], name='profilelikes_liked_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['liker_id'], ['profiles.id'], name='profilelikes_liker_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('liker_id', 'liked_id', name='profilelikes_pkey')
    )
    # ### end Alembic commands ###
